# Important: you have to manually delete mpi* from the /envs/optwrf/bin dir
name: optwrf
channels:
  - defaults
  - conda-forge
dependencies:
  - cartopy
  - esmpy=7.1.0
  - jupyter
  - nco
  - netCDF4
  - pyresample
  - pytest
  - python=3.7
  - pyyaml
  - requests
  - scipy
  - siphon
  - wrf-python
  - xarray
#  - xesmf
#  - metpy