# Important: you have to manually delete mpi* from the /envs/optwrf/bin dir
name: optwrf
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - pytest
  - pyyaml
  - requests
  - siphon
  - scipy
  - xarray
  - wrf-python
  - cartopy
  - iris
  - xesmf
  - esmpy=7.1.0
  - pyresample
#  - metpy