# Important: you have to manually delete mpi* from the /envs/optwrf/bin dir
name: optwrf
channels:
  - conda-forge
dependencies:
  - cartopy=0.17.0
  - esmf=8.0.1
  - esmpy=8.0.1
  - nco
  - netCDF4=1.5.3
  - pip
  - pyresample
  - python=3.7
  - pytest
  - pyyaml
  - requests
  - scipy
  - siphon
  - wrf-python
  - xarray=0.16.0
  - pip:
    - git+https://github.com/pangeo-data/xESMF.git
