# Important: you have to manually delete mpi* from the /envs/optwrf/bin dir
name: optwrf
channels:
  - conda-forge
dependencies:
  - cartopy=0.17.0
  - esmf=8.0.1
  - esmpy=8.0.1
  - ncl=6.6.2
  - nco=4.9.3
  - netCDF4=1.5.3
  - pip=20.2.2
  - pyresample=1.16.0
  - python=3.7
  - pytest=6.0.1
  - pyyaml=5.3.1
  - requests=2.24.0
  - scipy=1.5.2
  - siphon=0.8.0
  - wrf-python=1.3.2
  - xarray=0.16.0
  - pip:
    - git+https://github.com/pangeo-data/xESMF.git
    - cdsapi
